apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateshift.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "gateshift.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateshift.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gateshift.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:8081
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.githubToken.existingSecret }}
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.githubToken.existingSecret }}
                  key: {{ .Values.githubToken.key }}
          {{- end }}
