package nginx

// Well-known NGINX Ingress / cert-manager annotation keys.
const (
	AnnRewriteTarget            = "nginx.ingress.kubernetes.io/rewrite-target"
	AnnSSLRedirect              = "nginx.ingress.kubernetes.io/ssl-redirect"
	AnnForceSSLRedirect         = "nginx.ingress.kubernetes.io/force-ssl-redirect"
	AnnPermanentRedirect        = "nginx.ingress.kubernetes.io/permanent-redirect"
	AnnTemporalRedirect         = "nginx.ingress.kubernetes.io/temporal-redirect"
	AnnLimitRPS                 = "nginx.ingress.kubernetes.io/limit-rps"
	AnnLimitRPM                 = "nginx.ingress.kubernetes.io/limit-rpm"
	AnnLimitConnections         = "nginx.ingress.kubernetes.io/limit-connections"
	AnnCORSEnable               = "nginx.ingress.kubernetes.io/enable-cors"
	AnnCORSAllowOrigin          = "nginx.ingress.kubernetes.io/cors-allow-origin"
	AnnCORSAllowMethods         = "nginx.ingress.kubernetes.io/cors-allow-methods"
	AnnCORSAllowHeaders         = "nginx.ingress.kubernetes.io/cors-allow-headers"
	AnnCORSExposeHeaders        = "nginx.ingress.kubernetes.io/cors-expose-headers"
	AnnCORSAllowCredentials     = "nginx.ingress.kubernetes.io/cors-allow-credentials"
	AnnConfigurationSnippet     = "nginx.ingress.kubernetes.io/configuration-snippet"
	AnnServerSnippet            = "nginx.ingress.kubernetes.io/server-snippet"
	AnnModsecuritySnippet       = "nginx.ingress.kubernetes.io/modsecurity-snippet"
	AnnAuthURL                  = "nginx.ingress.kubernetes.io/auth-url"
	AnnAuthSignin               = "nginx.ingress.kubernetes.io/auth-signin"
	AnnAuthTLSSecret            = "nginx.ingress.kubernetes.io/auth-tls-secret"
	AnnAffinity                 = "nginx.ingress.kubernetes.io/affinity"
	AnnSessionCookieName        = "nginx.ingress.kubernetes.io/session-cookie-name"
	AnnWhitelistSourceRange     = "nginx.ingress.kubernetes.io/whitelist-source-range"
	AnnDenylistSourceRange      = "nginx.ingress.kubernetes.io/denylist-source-range"
	AnnProxyBodySize            = "nginx.ingress.kubernetes.io/proxy-body-size"
	AnnProxyReadTimeout         = "nginx.ingress.kubernetes.io/proxy-read-timeout"
	AnnProxySendTimeout         = "nginx.ingress.kubernetes.io/proxy-send-timeout"
	AnnBackendProtocol          = "nginx.ingress.kubernetes.io/backend-protocol"
	AnnCanary                   = "nginx.ingress.kubernetes.io/canary"
	AnnCanaryWeight             = "nginx.ingress.kubernetes.io/canary-weight"
	AnnCanaryByHeader           = "nginx.ingress.kubernetes.io/canary-by-header"
	AnnUseRegex                 = "nginx.ingress.kubernetes.io/use-regex"
	AnnUpstreamHashBy           = "nginx.ingress.kubernetes.io/upstream-hash-by"
	AnnCertManagerIssuer        = "cert-manager.io/issuer"
	AnnCertManagerClusterIssuer = "cert-manager.io/cluster-issuer"
)
