apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sticky
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: GATESHIFTROUTE
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-samesite: Lax
spec:
  ingressClassName: nginx
  rules:
    - host: sticky.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sticky
                port:
                  number: 80
