// Package gitops creates migration pull requests (GitHub) or local dry-run artifacts.
package gitops

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/gateshift/gateshift/pkg/ir"
)

// PRRequest describes an automated migration PR.
type PRRequest struct {
	Repo         string // owner/name
	BaseBranch   string
	BranchPrefix string
	Title        string
	ManifestYAML []byte
	Bundle       *ir.MigrationBundle
	IngressName  string
	DryRunDir    string // if set (or no token), write files instead of opening a PR
	GitHubToken  string
}

// PRResult is the outcome of CreateMigrationPR.
type PRResult struct {
	URL    string
	Branch string
	DryRun bool
	Files  []string
	Body   string
}

// CreateMigrationPR opens a GitHub PR when a token is present; otherwise writes a dry-run folder.
func CreateMigrationPR(ctx context.Context, req PRRequest) (*PRResult, error) {
	if req.BranchPrefix == "" {
		req.BranchPrefix = "gateshift/"
	}
	if req.BaseBranch == "" {
		req.BaseBranch = "main"
	}
	branch := fmt.Sprintf("%s%s-%s", req.BranchPrefix, sanitize(req.IngressName), time.Now().UTC().Format("20060102-150405"))
	if req.Title == "" {
		req.Title = fmt.Sprintf("GateShift: migrate Ingress %s to Gateway API", req.IngressName)
	}
	body := BuildPRBody(req.Bundle, req.IngressName)

	token := req.GitHubToken
	if token == "" {
		token = os.Getenv("GITHUB_TOKEN")
	}

	// Prefer dry-run when no token or DryRunDir forced.
	if token == "" || req.DryRunDir != "" {
		dir := req.DryRunDir
		if dir == "" {
			dir = filepath.Join(".", ".gateshift-pr", sanitize(req.IngressName))
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, err
		}
		manifestPath := filepath.Join(dir, "gateway-api.yaml")
		bodyPath := filepath.Join(dir, "PULL_REQUEST.md")
		if err := os.WriteFile(manifestPath, req.ManifestYAML, 0o644); err != nil {
			return nil, err
		}
		if err := os.WriteFile(bodyPath, []byte(body), 0o644); err != nil {
			return nil, err
		}
		return &PRResult{
			DryRun: true,
			Branch: branch,
			Body:   body,
			Files:  []string{manifestPath, bodyPath},
			URL:    "dry-run://" + dir,
		}, nil
	}

	return createGitHubPR(ctx, token, req, branch, body)
}

// BuildPRBody renders a markdown audit table for PR descriptions.
func BuildPRBody(bundle *ir.MigrationBundle, ingressName string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## GateShift migration: `%s`\n\n", ingressName)
	fmt.Fprintf(&b, "This PR was generated by GateShift. Review Level 2/3 findings before merge.\n\n")
	if bundle != nil {
		d, p, u := bundle.Summary()
		fmt.Fprintf(&b, "### Audit summary\n\n")
		fmt.Fprintf(&b, "| Direct (L1) | Policy (L2) | Manual (L3) |\n|---:|---:|---:|\n| %d | %d | %d |\n\n", d, p, u)
		fmt.Fprintf(&b, "### Findings\n\n")
		fmt.Fprintf(&b, "| Level | Status | Annotation | Notes |\n|---|---|---|---|\n")
		for _, f := range bundle.Findings {
			fmt.Fprintf(&b, "| L%d | %s | `%s` | %s |\n", f.Level, f.Status, f.Key, escapeMD(f.Message))
		}
		fmt.Fprintf(&b, "\n")
	}
	fmt.Fprintf(&b, "### Checklist\n\n")
	fmt.Fprintf(&b, "- [ ] Conformance report reviewed for target controller\n")
	fmt.Fprintf(&b, "- [ ] Level 3 snippets rewritten or accepted as debt\n")
	fmt.Fprintf(&b, "- [ ] Canary / dual-run plan for production cutover\n")
	return b.String()
}

func sanitize(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.ReplaceAll(s, " ", "-")
	return s
}

func escapeMD(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
